### ISSUE TITLE
AVIRIS Preprocessing

### ISSUE THREAD

**Issue by pomadchin** [azavea/nasa-hyperspectral#54]
An Activator Epic to track the AVIRIS preprocessing component development.

Modules development:
- [x] AVIRIS Scenes activation module
    - [x] [AVIRIS L2 Scenes activation module](https://github.com/azavea/nasa-hyperspectral/issues/55)
    - [x] [AVIRIS L1 Scenes activation module](https://github.com/azavea/nasa-hyperspectral/issues/61)
    - [x] [Skip AVIRIS scenes that have already been pre-processed](https://github.com/azavea/nasa-hyperspectral/issues/68)
- [x] [AVIRIS Scenes clip module](https://github.com/azavea/nasa-hyperspectral/issues/56)

These two issues above would in fact take care of the input and output messages formats of both modules. 

Additional development environment tasks:
- [x] [Initialize a base development environment](https://github.com/azavea/nasa-hyperspectral/issues/48)
- [x] [Add Step Functions infrastructure for a stub workflow](https://github.com/azavea/nasa-hyperspectral/issues/39)

**Comment by pomadchin** [comment]
Closing this Epic, since all tasks seems to be completed. If needed we can reopen it and / or create more issues needed.
